max_obstacle_height: 0.60
obstacle_range: 2.5
raytrace_range: 3.0
footprint_padding: 0.0
robot_radius: 0.15
# voxel map configuration; z-voxels 0 are filled by bumpers and 1 by laser scan (kinect)
map_type: voxel
origin_z: 0.0
z_resolution: 0.15
z_voxels: 2
global_frame: /map
robot_base_frame: /base_footprint
transform_tolerance: 2.0