#!/usr/bin/env python

import rospy

import kuri_navigation

if __name__ == '__main__':

    rospy.init_node('mapping_controller')

    mapping_controller = kuri_navigation.MappingController()

    try:
        mapping_controller.run()
    finally:
        mapping_controller.shutdown()