#!/usr/bin/env python

import kuri_navigation
import rospy

if __name__ == '__main__':

    rospy.init_node('nav_controller')

    nav_controller = kuri_navigation.MayNavController()

    try:
        nav_controller.run()
    finally:
        nav_controller.shutdown()
