#!/usr/bin/env python
import sys

import rospy

import kuri_navigation

if __name__ == '__main__':

    rospy.init_node('nav_controller')

    nav_controller = kuri_navigation.MayNavController()

    try:
        nav_controller.run()
    finally:
        nav_controller.shutdown()
