#!/usr/bin/env python

import kuri_navigation
import rospy

if __name__ == '__main__':

    rospy.init_node('safety_controller')

    safety_controller = kuri_navigation.SafetyController()

    try:
        safety_controller.run()
    finally:
        safety_controller.shutdown()
