#!/usr/bin/env python
from kuri_api.record import LivePhoto

from threading import Event, Thread
from mayvision.services import Vision
import time
from functools import partial
import subprocess

photo_captured = Event()

# Trigger a 3 second capture
ph = LivePhoto(Vision(), None, None, None, vid_channel=2)


def audio_record(file_name):
    p = subprocess.Popen(["parecord", file_name])
    while True:
        time.sleep(.01)
        if photo_captured.is_set():
            p.terminate()
            break


def decision():
    ph.save()
    photo_captured.set()


counter = 0
while True:
    duration = input("Enter recording duration: ")
    print("")
    print("Capturing...")
    ph.capture(str(counter), duration, cb=decision)
    audio_cap_thread = Thread(target=partial(audio_record, str(counter) + ".wav"))
    audio_cap_thread.start()
    photo_captured.wait()
    audio_cap_thread.join()
    photo_captured.clear()
    counter += 1

ph.shutdown()
