#!/usr/bin/env python

"""This is an example of a simple sound capture script.

 You won't be able to run this script while `audio_realtime` is
 using the microphones.

 The script opens an ALSA pcm device for sound capture, sets
 various attributes of the capture, and reads in a loop,
 writing the data to standard out.

 To test it out do the following:
 python recordtest.py out.wav # talk to the microphone
 aplay -r 48000 -f S16_LE -c 1 out.wav"""


from __future__ import print_function

import sys
import time
import getopt
import alsaaudio
import wave


def usage():
    print('usage: record_demo.py [-d <device>] <file>', file=sys.stderr)
    sys.exit(2)


if __name__ == '__main__':

    device = 'default'

    opts, args = getopt.getopt(sys.argv[1:], 'd:')
    for o, a in opts:
        if o == '-d':
            device = a

    if not args:
        usage()

    # Open the device in nonblocking capture mode. The last argument could
    # just as well have been zero for blocking mode. Then we could have
    # left out the sleep call in the bottom of the loop
    # inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NONBLOCK, device)
    # inp = alsaaudio.PCM(type=alsaaudio.PCM_CAPTURE) # Works? (Doesn't cause errors)
    inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NONBLOCK)
    # inp = alsaaudio.PCM(type=alsaaudio.PCM_CAPTURE, device=device)

    # Set attributes: Mono, 48000 Hz, 16 bit little endian samples
    inp.setchannels(1)
    inp.setrate(48000)
    inp.setformat(alsaaudio.PCM_FORMAT_S16_LE)

    # The period size controls the internal number of frames per period.
    # The significance of this parameter is documented in the ALSA api.
    # For our purposes, it is suficcient to know that reads from the device
    # will return this many frames. Each frame being 2 bytes long.
    # This means that the reads below will return either 320 bytes of data
    # or 0 bytes of data. The latter is possible because we are in nonblocking
    # mode.
    inp.setperiodsize(160)

    f = wave.open(args[0], 'wb')
    f.setnchannels(1)
    f.setframerate(48000)
    f.setsampwidth(2)
    # Kill the program whenever you're done recording
    while True:
        l, data = inp.read()
        if l:
            f.writeframes(b''.join(data))
            time.sleep(.001)
